"""Location Consolidation — maps multiple WhsCodes to a single display location.

Business context: The same physical retail location (e.g., "Siam Paragon")
has multiple WhsCodes because of different GP commission tiers (GP25, GP30,
GP33, Art Toy, promotional rates, etc.). For analytics purposes, we need to
consolidate these into a single location identity so that:
- Location performance rankings compare actual physical locations
- Item-at-location trends show the full picture at each store
- On-hand and sales are summed across all sub-codes

The mapping is stored in app/data/location_consolidation.json, generated by
scripts/generate_location_mapping.py. Any WhsCode NOT in the mapping falls
through to its original WhsName (never dropped).

Usage:
    from app.utils.location_consolidation import get_consolidated_name, add_consolidated_column

    # Single lookup
    display_name = get_consolidated_name("CCTLPN33", whs_lookup)

    # Add column to DataFrame for groupby
    df = add_consolidated_column(df, whs_lookup)
    # Now df["ConsolidatedLocation"] is available for groupby
"""
from __future__ import annotations

import json
import os
from functools import lru_cache
from typing import Optional

import pandas as pd

_MAPPING_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "location_consolidation.json")


@lru_cache(maxsize=1)
def _load_mapping() -> dict[str, str]:
    """Load the WhsCode -> consolidated display name mapping."""
    try:
        with open(_MAPPING_PATH, encoding="utf-8") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def get_consolidated_name(
    whs_code: str,
    whs_lookup: Optional[dict[str, str]] = None,
) -> str:
    """Return the consolidated display name for a WhsCode.

    Falls back to whs_lookup (WhsCode -> WhsName) if code is not in the
    consolidation mapping. Falls back to the raw code if not in whs_lookup.
    """
    mapping = _load_mapping()
    code = str(whs_code).strip()
    consolidated = mapping.get(code)
    if consolidated:
        return consolidated
    if whs_lookup:
        return whs_lookup.get(code, code)
    return code


def add_consolidated_column(
    df: pd.DataFrame,
    whs_lookup: Optional[dict[str, str]] = None,
    whs_col: str = "WhsCode",
    new_col: str = "ConsolidatedLocation",
) -> pd.DataFrame:
    """Add a ConsolidatedLocation column to a DataFrame.

    Maps each WhsCode to its consolidated display name using the JSON mapping.
    Any code not in the mapping falls through to its WhsName or raw code.

    Parameters
    ----------
    df : DataFrame with a WhsCode column
    whs_lookup : dict of WhsCode -> WhsName (raw names)
    whs_col : name of the WhsCode column (default "WhsCode")
    new_col : name of the new column to add (default "ConsolidatedLocation")
    """
    if df.empty or whs_col not in df.columns:
        df[new_col] = ""
        return df
    mapping = _load_mapping()
    lookup = whs_lookup or {}

    def _resolve(code):
        c = str(code).strip()
        return mapping.get(c) or lookup.get(c, c)

    df = df.copy()
    df[new_col] = df[whs_col].apply(_resolve)
    return df


def get_all_codes_for_location(consolidated_name: str) -> list[str]:
    """Return all WhsCodes that map to a given consolidated location name."""
    mapping = _load_mapping()
    return [code for code, name in mapping.items() if name == consolidated_name]


def get_mapping() -> dict[str, str]:
    """Return the full WhsCode -> consolidated name mapping."""
    return dict(_load_mapping())
